services:
  - name: my-fastapi-ollama-service
    type: web
    runtime: python          # Bắt buộc
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
