services:
  - name: my-fastapi-ollama-service
    type: web
    runtime: python          # Bắt buộc
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:8001
